language: node_js
node_js:
- 0.10.33
before_install: npm install -g grunt-cli
install: npm install
script: grunt
addons:
  sauce_connect: true
env:
  global:
  - secure: cbmYhWUF7hk208OPPixNKTfe63jZ4VVY/VwAHXZtBFXCEtiLuBeDETzG2+ex0THNHwUkfAaq5FxhrOGzJjoIAcQsYPUEKQWoXPtJ3RyaVsWpCxu20no/zahTcXQCZaPwkOy2ShWNmrfTPrXyShcnfYe1Eqg9u8Zv2HhQ4q/AvwA=
  - secure: f2lqc9W2ED61/iXHCU/wMuONRexVNXg8cFo433R+/ET8IemCHFPnz5QuwqyaRZscYNaRcrF2jcAkL0KplLt0bOnk1UEmWMSJ1TTi/Q0CDQKl7L/WGT38L5RfEiZrhmpOhHPBx5HXH3u4yiNnc1qTww2irfLSHNmEI/4+15hLy8w=
