language: node_js
node_js:
- 0.10.33
before_install: npm install -g grunt-cli
install: npm install
script: grunt
addons:
  sauce_connect: true
env:
  global:
  - secure: REBl6IrRSaFg/UNHpRBAb18JgulJUdxQ4FfP1B7sJbZseJOEr2VKwOJn1wurb12dQya88o7hW2luQhi37mnqzsecKN4hoeXzsiF9IVQTmbmRInpkWa8iJYjQrXwtJS8vz9BXodotqzVMAetaEHvAmb6zBK856wJH9KmT+jRTZCs=
  - secure: J5YbdCckQBpGmnrzyZJvilFcWjQtf9Uo634vAYuZwl8OhUZS/u14lo0IB2sppB5qAbpot1QzDfXeihn8b+Mqneca9VIHYhYrkkO/YxBCRztuLjxDO22TWLTmtz0w1K/dssJK4o7Vd3A34odc3k5XBukuB5z+I0kIOJYoS5Hlgbw=
